//
//  furniture.swift
//  Sales
//
//  Created by José Ruiz on 8/7/24.
//

import Foundation

let furniture: Categories = [
    Mi(name: "Furniture"): [
        Ni(name: "Living Room"): [
            Xi(name: "Sofa"),
            Xi(name: "Sectional Sofa"),
            Xi(name: "Loveseat"),
            Xi(name: "Recliner"),
            Xi(name: "Armchair"),
            Xi(name: "Ottoman"),
            Xi(name: "Coffee Table"),
            Xi(name: "End Table"),
            Xi(name: "Console Table"),
            Xi(name: "TV Stand"),
            Xi(name: "Entertainment Center"),
            Xi(name: "Bookshelf"),
            Xi(name: "Display Cabinet"),
            Xi(name: "Room Divider"),
            Xi(name: "Living Room Set"),
            Xi(name: "Chaise Lounge"),
            Xi(name: "Electric Fireplace"),
            Xi(name: "Wall Shelf")
        ],
        Ni(name: "Bedroom"): [
            Xi(name: "Bed"),
            Xi(name: "Platform Bed"),
            Xi(name: "Storage Bed"),
            Xi(name: "Canopy Bed"),
            Xi(name: "Sleigh Bed"),
            Xi(name: "Bunk Bed"),
            Xi(name: "Daybed"),
            Xi(name: "Nightstand"),
            Xi(name: "Dresser"),
            Xi(name: "Chest of Drawers"),
            Xi(name: "Wardrobe"),
            Xi(name: "Armoire"),
            Xi(name: "Vanity"),
            Xi(name: "Desk"),
            Xi(name: "Chair"),
            Xi(name: "Bench"),
            Xi(name: "Bedroom Set"),
            Xi(name: "Mirror"),
            Xi(name: "Headboard")
        ],
        Ni(name: "Office"): [
            Xi(name: "Desk"),
            Xi(name: "Writing Desk"),
            Xi(name: "Computer Desk"),
            Xi(name: "Standing Desk"),
            Xi(name: "Corner Desk"),
            Xi(name: "Executive Desk"),
            Xi(name: "Office Chair"),
            Xi(name: "Ergonomic Chair"),
            Xi(name: "Conference Chair"),
            Xi(name: "Bookshelf"),
            Xi(name: "Filing Cabinet"),
            Xi(name: "Desk Lamp"),
            Xi(name: "Desk Organizer"),
            Xi(name: "Office Sofa"),
            Xi(name: "Conference Table"),
            Xi(name: "Office Partition"),
            Xi(name: "Printer Stand"),
            Xi(name: "Storage Cabinet"),
            Xi(name: "Whiteboard")
        ],
        Ni(name: "Dining Room"): [
            Xi(name: "Dining Table"),
            Xi(name: "Dining Chair"),
            Xi(name: "Dining Bench"),
            Xi(name: "Bar Stool"),
            Xi(name: "Buffet"),
            Xi(name: "Sideboard"),
            Xi(name: "China Cabinet"),
            Xi(name: "Dining Room Set"),
            Xi(name: "Bar Cart"),
            Xi(name: "Dining Hutch"),
            Xi(name: "Kitchen Island"),
            Xi(name: "High Top Table"),
            Xi(name: "Low Dining Table"),
            Xi(name: "Counter Height Table")
        ],
        Ni(name: "Outdoor"): [
            Xi(name: "Patio Set"),
            Xi(name: "Outdoor Sofa"),
            Xi(name: "Outdoor Chair"),
            Xi(name: "Adirondack Chair"),
            Xi(name: "Hammock"),
            Xi(name: "Grill"),
            Xi(name: "Fire Pit"),
            Xi(name: "Outdoor Table"),
            Xi(name: "Picnic Table"),
            Xi(name: "Umbrella"),
            Xi(name: "Gazebo"),
            Xi(name: "Pergola"),
            Xi(name: "Outdoor Storage Box"),
            Xi(name: "Patio Heater"),
            Xi(name: "Outdoor Bar"),
            Xi(name: "Outdoor Dining Set"),
            Xi(name: "Garden Bench"),
            Xi(name: "Deck Box"),
            Xi(name: "Lounge Chair")
        ],
        Ni(name: "Storage & Organization"): [
            Xi(name: "Wardrobe"),
            Xi(name: "Closet System"),
            Xi(name: "Shoe Rack"),
            Xi(name: "Coat Rack"),
            Xi(name: "Storage Bench"),
            Xi(name: "Storage Cabinet"),
            Xi(name: "Bookshelf"),
            Xi(name: "Wall Shelf"),
            Xi(name: "Utility Shelf"),
            Xi(name: "Storage Ottoman"),
            Xi(name: "Toy Chest"),
            Xi(name: "Jewelry Armoire"),
            Xi(name: "Pantry Cabinet"),
            Xi(name: "Laundry Hamper"),
            Xi(name: "File Cabinet"),
            Xi(name: "Desk Organizer"),
            Xi(name: "Storage Bin")
        ],
        Ni(name: "Kids' Furniture"): [
            Xi(name: "Kids' Bed"),
            Xi(name: "Bunk Bed"),
            Xi(name: "Loft Bed"),
            Xi(name: "Kids' Table"),
            Xi(name: "Kids' Chair"),
            Xi(name: "Kids' Bookshelf"),
            Xi(name: "Toy Storage"),
            Xi(name: "Kids' Desk"),
            Xi(name: "Kids' Dresser"),
            Xi(name: "Kids' Nightstand"),
            Xi(name: "Kids' Sofa"),
            Xi(name: "Kids' Bean Bag"),
            Xi(name: "Kids' Activity Table"),
            Xi(name: "Crib"),
            Xi(name: "Changing Table"),
            Xi(name: "Kids' Wardrobe")
        ]
    ]
]
