//
//  hardwareStore.swift
//  Sales
//
//  Created by José Ruiz on 8/7/24.
//

import Foundation

let hardwareStore: Categories = [
    Mi(name: "Hardware Store"): [
        Ni(name: "Tools"): [
            Xi(name: "Hammer"),
            Xi(name: "Screwdriver"),
            Xi(name: "Wrench"),
            Xi(name: "Pliers"),
            Xi(name: "Drill"),
            Xi(name: "Saw"),
            Xi(name: "Tape Measure"),
            Xi(name: "Level"),
            Xi(name: "Chisel"),
            Xi(name: "Utility Knife"),
            Xi(name: "Socket Set"),
            Xi(name: "Allen Wrenches"),
            Xi(name: "Multimeter"),
            Xi(name: "Circular Saw"),
            Xi(name: "Jigsaw"),
            Xi(name: "Angle Grinder"),
            Xi(name: "Toolbox"),
            Xi(name: "Work Bench"),
            Xi(name: "Clamp"),
            Xi(name: "Sander")
        ],
        Ni(name: "Building Materials"): [
            Xi(name: "Lumber"),
            Xi(name: "Cement"),
            Xi(name: "Bricks"),
            Xi(name: "Tiles"),
            Xi(name: "Insulation"),
            Xi(name: "Drywall"),
            Xi(name: "Concrete"),
            Xi(name: "Plywood"),
            Xi(name: "Roofing Material"),
            Xi(name: "Paint"),
            Xi(name: "Sand"),
            Xi(name: "Gravel"),
            Xi(name: "Sheetrock"),
            Xi(name: "Rebar"),
            Xi(name: "Mortar"),
            Xi(name: "Asphalt"),
            Xi(name: "Flooring"),
            Xi(name: "Siding"),
            Xi(name: "Plaster"),
            Xi(name: "Stucco")
        ],
        Ni(name: "Plumbing"): [
            Xi(name: "Pipes"),
            Xi(name: "Faucets"),
            Xi(name: "Valves"),
            Xi(name: "Fittings"),
            Xi(name: "Water Heater"),
            Xi(name: "Sump Pump"),
            Xi(name: "Toilet"),
            Xi(name: "Sink"),
            Xi(name: "Shower Head"),
            Xi(name: "Pipe Insulation"),
            Xi(name: "Hose Bib"),
            Xi(name: "Water Filter"),
            Xi(name: "Water Softener"),
            Xi(name: "Drain Cleaner"),
            Xi(name: "Plunger"),
            Xi(name: "Pipe Wrench"),
            Xi(name: "PVC Pipe"),
            Xi(name: "Copper Pipe"),
            Xi(name: "PEX Pipe"),
            Xi(name: "Pipe Cutter")
        ],
        Ni(name: "Electrical"): [
            Xi(name: "Wiring"),
            Xi(name: "Outlets"),
            Xi(name: "Switches"),
            Xi(name: "Circuit Breaker"),
            Xi(name: "Light Fixtures"),
            Xi(name: "Extension Cord"),
            Xi(name: "Batteries"),
            Xi(name: "Smoke Detector"),
            Xi(name: "CO Detector"),
            Xi(name: "Doorbell"),
            Xi(name: "Fuse"),
            Xi(name: "Light Bulbs"),
            Xi(name: "Surge Protector"),
            Xi(name: "Electrical Tape"),
            Xi(name: "Wire Nuts"),
            Xi(name: "Conduit"),
            Xi(name: "Junction Box"),
            Xi(name: "Voltage Tester"),
            Xi(name: "Grounding Rod"),
            Xi(name: "Dimmer Switch")
        ],
        Ni(name: "Hardware"): [
            Xi(name: "Nails"),
            Xi(name: "Screws"),
            Xi(name: "Bolts"),
            Xi(name: "Nuts"),
            Xi(name: "Washers"),
            Xi(name: "Anchors"),
            Xi(name: "Brackets"),
            Xi(name: "Hinges"),
            Xi(name: "Locks"),
            Xi(name: "Door Knobs"),
            Xi(name: "Cabinet Hardware"),
            Xi(name: "Drawer Slides"),
            Xi(name: "Hooks"),
            Xi(name: "Chains"),
            Xi(name: "Rope"),
            Xi(name: "Wire"),
            Xi(name: "Zip Ties"),
            Xi(name: "Spring"),
            Xi(name: "Gate Hardware")
        ],
        Ni(name: "Paint & Supplies"): [
            Xi(name: "Interior Paint"),
            Xi(name: "Exterior Paint"),
            Xi(name: "Primer"),
            Xi(name: "Stain"),
            Xi(name: "Varnish"),
            Xi(name: "Paint Brushes"),
            Xi(name: "Paint Rollers"),
            Xi(name: "Paint Trays"),
            Xi(name: "Painter's Tape"),
            Xi(name: "Drop Cloths"),
            Xi(name: "Paint Sprayer"),
            Xi(name: "Sandpaper"),
            Xi(name: "Putty Knife"),
            Xi(name: "Paint Stripper"),
            Xi(name: "Caulk"),
            Xi(name: "Caulk Gun"),
            Xi(name: "Ladder"),
            Xi(name: "Paint Thinner")
        ],
        Ni(name: "Gardening & Landscaping"): [
            Xi(name: "Lawn Mower"),
            Xi(name: "Leaf Blower"),
            Xi(name: "Hedge Trimmer"),
            Xi(name: "Shovel"),
            Xi(name: "Rake"),
            Xi(name: "Hoe"),
            Xi(name: "Garden Fork"),
            Xi(name: "Watering Can"),
            Xi(name: "Hose"),
            Xi(name: "Sprinkler"),
            Xi(name: "Wheelbarrow"),
            Xi(name: "Garden Gloves"),
            Xi(name: "Pruning Shears"),
            Xi(name: "Lawn Edger"),
            Xi(name: "Compost Bin"),
            Xi(name: "Fertilizer"),
            Xi(name: "Mulch"),
            Xi(name: "Grass Seed"),
            Xi(name: "Plant Pots")
        ]
    ]
]
