//
//  home.swift
//  Sales
//
//  Created by José Ruiz on 8/7/24.
//

import Foundation

let home: Categories = [
    Mi(name: "Home"): [
        Ni(name: "Living Room"): [
            Xi(name: "Sofa"),
            Xi(name: "Sectional Sofa"),
            Xi(name: "Loveseat"),
            Xi(name: "Recliner"),
            Xi(name: "Armchair"),
            Xi(name: "Ottoman"),
            Xi(name: "Coffee Table"),
            Xi(name: "End Table"),
            Xi(name: "Console Table"),
            Xi(name: "TV Stand"),
            Xi(name: "Entertainment Center"),
            Xi(name: "Bookshelf"),
            Xi(name: "Display Cabinet"),
            Xi(name: "Room Divider"),
            Xi(name: "Electric Fireplace"),
            Xi(name: "Wall Shelf"),
            Xi(name: "Rug"),
            Xi(name: "Lamp"),
            Xi(name: "Curtains"),
            Xi(name: "Throw Pillows")
        ],
        Ni(name: "Bedroom"): [
            Xi(name: "Bed"),
            Xi(name: "Platform Bed"),
            Xi(name: "Storage Bed"),
            Xi(name: "Canopy Bed"),
            Xi(name: "Sleigh Bed"),
            Xi(name: "Bunk Bed"),
            Xi(name: "Daybed"),
            Xi(name: "Nightstand"),
            Xi(name: "Dresser"),
            Xi(name: "Chest of Drawers"),
            Xi(name: "Wardrobe"),
            Xi(name: "Armoire"),
            Xi(name: "Vanity"),
            Xi(name: "Desk"),
            Xi(name: "Chair"),
            Xi(name: "Bench"),
            Xi(name: "Bedroom Set"),
            Xi(name: "Mirror"),
            Xi(name: "Headboard"),
            Xi(name: "Mattress"),
            Xi(name: "Bedding"),
            Xi(name: "Closet Organizer"),
            Xi(name: "Lamp"),
            Xi(name: "Rug"),
            Xi(name: "Curtains")
        ],
        Ni(name: "Kitchen"): [
            Xi(name: "Refrigerator"),
            Xi(name: "Microwave"),
            Xi(name: "Dishwasher"),
            Xi(name: "Oven"),
            Xi(name: "Stove"),
            Xi(name: "Blender"),
            Xi(name: "Toaster"),
            Xi(name: "Coffee Maker"),
            Xi(name: "Slow Cooker"),
            Xi(name: "Air Fryer"),
            Xi(name: "Mixer"),
            Xi(name: "Food Processor"),
            Xi(name: "Electric Kettle"),
            Xi(name: "Juicer"),
            Xi(name: "Grill"),
            Xi(name: "Rice Cooker"),
            Xi(name: "Pressure Cooker"),
            Xi(name: "Sous Vide"),
            Xi(name: "Wine Cooler"),
            Xi(name: "Ice Maker"),
            Xi(name: "Kitchen Island"),
            Xi(name: "Pantry Cabinet"),
            Xi(name: "Bar Stool"),
            Xi(name: "Dish Rack"),
            Xi(name: "Cutlery Set"),
            Xi(name: "Cookware Set"),
            Xi(name: "Bakeware Set"),
            Xi(name: "Kitchen Utensils"),
            Xi(name: "Storage Containers"),
            Xi(name: "Spice Rack")
        ],
        Ni(name: "Bathroom"): [
            Xi(name: "Shower Curtain"),
            Xi(name: "Towel Rack"),
            Xi(name: "Toothbrush Holder"),
            Xi(name: "Soap Dispenser"),
            Xi(name: "Bath Mat"),
            Xi(name: "Shower Head"),
            Xi(name: "Bathroom Mirror"),
            Xi(name: "Toilet Brush"),
            Xi(name: "Plunger"),
            Xi(name: "Storage Cabinet"),
            Xi(name: "Bathroom Vanity"),
            Xi(name: "Medicine Cabinet"),
            Xi(name: "Bathroom Shelves"),
            Xi(name: "Laundry Hamper"),
            Xi(name: "Shower Caddy"),
            Xi(name: "Bath Towels"),
            Xi(name: "Hand Towels"),
            Xi(name: "Washcloths"),
            Xi(name: "Bathrobe"),
            Xi(name: "Shower Chair"),
            Xi(name: "Toilet Paper Holder"),
            Xi(name: "Soap Dish"),
            Xi(name: "Trash Can"),
            Xi(name: "Bathroom Scale")
        ],
        Ni(name: "Dining Room"): [
            Xi(name: "Dining Table"),
            Xi(name: "Dining Chair"),
            Xi(name: "Dining Bench"),
            Xi(name: "Bar Stool"),
            Xi(name: "Buffet"),
            Xi(name: "Sideboard"),
            Xi(name: "China Cabinet"),
            Xi(name: "Dining Room Set"),
            Xi(name: "Bar Cart"),
            Xi(name: "Dining Hutch"),
            Xi(name: "Kitchen Island"),
            Xi(name: "High Top Table"),
            Xi(name: "Low Dining Table"),
            Xi(name: "Counter Height Table"),
            Xi(name: "Dining Room Rug"),
            Xi(name: "Dining Room Lamp"),
            Xi(name: "Wine Rack")
        ],
        Ni(name: "Home Office"): [
            Xi(name: "Desk"),
            Xi(name: "Office Chair"),
            Xi(name: "Bookshelf"),
            Xi(name: "Filing Cabinet"),
            Xi(name: "Desk Lamp"),
            Xi(name: "Standing Desk"),
            Xi(name: "Desk Organizer"),
            Xi(name: "Office Sofa"),
            Xi(name: "Conference Table"),
            Xi(name: "Office Partition"),
            Xi(name: "Printer Stand"),
            Xi(name: "Storage Cabinet"),
            Xi(name: "Whiteboard"),
            Xi(name: "Office Rug"),
            Xi(name: "Office Curtains"),
            Xi(name: "Office Wall Art")
        ],
        Ni(name: "Laundry Room"): [
            Xi(name: "Washing Machine"),
            Xi(name: "Dryer"),
            Xi(name: "Laundry Basket"),
            Xi(name: "Ironing Board"),
            Xi(name: "Iron"),
            Xi(name: "Drying Rack"),
            Xi(name: "Laundry Detergent"),
            Xi(name: "Fabric Softener"),
            Xi(name: "Stain Remover"),
            Xi(name: "Lint Roller"),
            Xi(name: "Clothes Steamer"),
            Xi(name: "Laundry Hamper"),
            Xi(name: "Laundry Room Shelves"),
            Xi(name: "Laundry Room Cabinets"),
            Xi(name: "Laundry Room Organizer")
        ]
    ]
]
