//
//  pharmacy.swift
//  Sales
//
//  Created by José Ruiz on 8/7/24.
//

import Foundation

let pharmacy: Categories = [
    Mi(name: "Pharmacy"): [
        Ni(name: "Medications"): [
            Xi(name: "Pain Relievers"),
            Xi(name: "Antibiotics"),
            Xi(name: "Antidepressants"),
            Xi(name: "Cold Medicine"),
            Xi(name: "Cough Syrup"),
            Xi(name: "Allergy Medicine"),
            Xi(name: "Antacids"),
            Xi(name: "Vitamins"),
            Xi(name: "Supplements"),
            Xi(name: "First Aid Kit"),
            Xi(name: "Antihistamines"),
            Xi(name: "Cough Drops"),
            Xi(name: "Laxatives"),
            Xi(name: "Anti-diarrheal"),
            Xi(name: "Motion Sickness Medicine"),
            Xi(name: "Sleeping Aids"),
            Xi(name: "Anti-fungal Creams"),
            Xi(name: "Anti-itch Creams"),
            Xi(name: "Hydrocortisone Cream"),
            Xi(name: "Antiseptic Creams"),
            Xi(name: "Hemorrhoid Treatments"),
            Xi(name: "Smoking Cessation Aids")
        ],
        Ni(name: "Personal Care"): [
            Xi(name: "Shampoo"),
            Xi(name: "Conditioner"),
            Xi(name: "Body Wash"),
            Xi(name: "Moisturizer"),
            Xi(name: "Deodorant"),
            Xi(name: "Toothpaste"),
            Xi(name: "Toothbrush"),
            Xi(name: "Mouthwash"),
            Xi(name: "Razor"),
            Xi(name: "Shaving Cream"),
            Xi(name: "Face Wash"),
            Xi(name: "Hand Soap"),
            Xi(name: "Lotion"),
            Xi(name: "Sunscreen"),
            Xi(name: "Lip Balm"),
            Xi(name: "Makeup Remover"),
            Xi(name: "Cotton Swabs"),
            Xi(name: "Cotton Balls"),
            Xi(name: "Nail Clippers"),
            Xi(name: "Hair Brush"),
            Xi(name: "Hair Gel"),
            Xi(name: "Hair Spray"),
            Xi(name: "Dental Floss"),
            Xi(name: "Denture Care"),
            Xi(name: "Mouth Guard"),
            Xi(name: "Foot Powder"),
            Xi(name: "Antiperspirant"),
            Xi(name: "Perfume"),
            Xi(name: "Aftershave")
        ],
        Ni(name: "Health Monitoring"): [
            Xi(name: "Blood Pressure Monitor"),
            Xi(name: "Thermometer"),
            Xi(name: "Glucose Meter"),
            Xi(name: "Pulse Oximeter"),
            Xi(name: "Body Scale"),
            Xi(name: "Fitness Tracker"),
            Xi(name: "Heart Rate Monitor"),
            Xi(name: "Sleep Tracker"),
            Xi(name: "Smart Scale"),
            Xi(name: "Personal ECG Monitor"),
            Xi(name: "Peak Flow Meter"),
            Xi(name: "Ovulation Kit"),
            Xi(name: "Pregnancy Test"),
            Xi(name: "Hearing Aid"),
            Xi(name: "Medical Alert System")
        ],
        Ni(name: "Baby Care"): [
            Xi(name: "Diapers"),
            Xi(name: "Baby Wipes"),
            Xi(name: "Baby Formula"),
            Xi(name: "Baby Lotion"),
            Xi(name: "Baby Shampoo"),
            Xi(name: "Baby Powder"),
            Xi(name: "Baby Bottles"),
            Xi(name: "Pacifiers"),
            Xi(name: "Baby Monitor"),
            Xi(name: "Baby Clothes"),
            Xi(name: "Baby Food"),
            Xi(name: "Baby Bath Tub"),
            Xi(name: "Baby Oil"),
            Xi(name: "Baby Cream"),
            Xi(name: "Diaper Rash Cream"),
            Xi(name: "Teething Gel"),
            Xi(name: "Nasal Aspirator"),
            Xi(name: "Bottle Warmer"),
            Xi(name: "Baby Carrier"),
            Xi(name: "Stroller"),
            Xi(name: "Car Seat"),
            Xi(name: "Baby Blanket"),
            Xi(name: "Baby Toys")
        ],
        Ni(name: "First Aid"): [
            Xi(name: "Bandages"),
            Xi(name: "Gauze Pads"),
            Xi(name: "Adhesive Tape"),
            Xi(name: "Antiseptic Wipes"),
            Xi(name: "Hydrogen Peroxide"),
            Xi(name: "Rubbing Alcohol"),
            Xi(name: "Antibiotic Ointment"),
            Xi(name: "Burn Cream"),
            Xi(name: "Cold Pack"),
            Xi(name: "Elastic Bandage"),
            Xi(name: "Finger Splints"),
            Xi(name: "Medical Gloves"),
            Xi(name: "Scissors"),
            Xi(name: "Tweezers"),
            Xi(name: "Thermometer"),
            Xi(name: "CPR Mask"),
            Xi(name: "Eye Wash"),
            Xi(name: "Cotton Swabs"),
            Xi(name: "First Aid Manual"),
            Xi(name: "Medical Tape"),
            Xi(name: "Sterile Dressings"),
            Xi(name: "Pain Relief Spray"),
            Xi(name: "Eye Patches")
        ],
        Ni(name: "Sexual Wellness"): [
            Xi(name: "Condoms"),
            Xi(name: "Lubricants"),
            Xi(name: "Pregnancy Tests"),
            Xi(name: "Ovulation Tests"),
            Xi(name: "Vaginal Moisturizers"),
            Xi(name: "Fertility Supplements"),
            Xi(name: "Menstrual Cups"),
            Xi(name: "Tampons"),
            Xi(name: "Sanitary Pads"),
            Xi(name: "Intimate Wash"),
            Xi(name: "Intimate Wipes"),
            Xi(name: "Sexual Enhancement Supplements"),
            Xi(name: "Personal Massagers"),
            Xi(name: "Sexual Health Books")
        ],
        Ni(name: "Elderly Care"): [
            Xi(name: "Adult Diapers"),
            Xi(name: "Walking Canes"),
            Xi(name: "Walker"),
            Xi(name: "Wheelchair"),
            Xi(name: "Shower Chair"),
            Xi(name: "Bed Pan"),
            Xi(name: "Incontinence Pads"),
            Xi(name: "Hearing Aids"),
            Xi(name: "Denture Care"),
            Xi(name: "Grab Bars"),
            Xi(name: "Raised Toilet Seat"),
            Xi(name: "Compression Socks"),
            Xi(name: "Magnifying Glass"),
            Xi(name: "Pill Organizer"),
            Xi(name: "Home Safety Products"),
            Xi(name: "Medical Alert System"),
            Xi(name: "Mobility Scooter"),
            Xi(name: "Blood Pressure Monitor")
        ],
        Ni(name: "Beauty & Skincare"): [
            Xi(name: "Facial Cleanser"),
            Xi(name: "Facial Toner"),
            Xi(name: "Facial Moisturizer"),
            Xi(name: "Sunscreen"),
            Xi(name: "Anti-Aging Cream"),
            Xi(name: "Face Masks"),
            Xi(name: "Acne Treatment"),
            Xi(name: "Eye Cream"),
            Xi(name: "Lip Balm"),
            Xi(name: "Body Lotion"),
            Xi(name: "Hand Cream"),
            Xi(name: "Foot Cream"),
            Xi(name: "Body Scrub"),
            Xi(name: "Exfoliator"),
            Xi(name: "Hair Removal Cream"),
            Xi(name: "Self-Tanner"),
            Xi(name: "Makeup"),
            Xi(name: "Makeup Remover"),
            Xi(name: "Perfume"),
            Xi(name: "Aftershave"),
            Xi(name: "Hair Dye"),
            Xi(name: "Hair Treatment"),
            Xi(name: "Nail Polish"),
            Xi(name: "Nail Polish Remover")
        ]
    ]
]

