//
//  sports.swift
//  Sales
//
//  Created by José Ruiz on 8/7/24.
//

import Foundation

let sports: Categories = [
    Mi(name: "Sports"): [
        Ni(name: "Team Sports"): [
            Xi(name: "Soccer Ball"),
            Xi(name: "Basketball"),
            Xi(name: "Baseball Glove"),
            Xi(name: "Football"),
            Xi(name: "Volleyball"),
            Xi(name: "Hockey Stick"),
            Xi(name: "Tennis Racket"),
            Xi(name: "Badminton Set"),
            Xi(name: "Cricket Bat"),
            Xi(name: "Rugby Ball"),
            Xi(name: "Soccer Cleats"),
            Xi(name: "Basketball Hoop"),
            Xi(name: "Baseball Bat"),
            Xi(name: "Baseball Helmet"),
            Xi(name: "Football Helmet"),
            Xi(name: "Volleyball Net"),
            Xi(name: "Hockey Puck"),
            Xi(name: "Tennis Balls"),
            Xi(name: "Badminton Shuttlecocks"),
            Xi(name: "Cricket Stumps"),
            Xi(name: "Rugby Boots"),
            Xi(name: "Team Jerseys"),
            Xi(name: "Sports Cones"),
            Xi(name: "Training Bibs"),
            Xi(name: "Goalkeeper Gloves")
        ],
        Ni(name: "Fitness"): [
            Xi(name: "Treadmill"),
            Xi(name: "Exercise Bike"),
            Xi(name: "Dumbbells"),
            Xi(name: "Resistance Bands"),
            Xi(name: "Yoga Mat"),
            Xi(name: "Kettlebells"),
            Xi(name: "Jump Rope"),
            Xi(name: "Foam Roller"),
            Xi(name: "Pull-Up Bar"),
            Xi(name: "Weight Bench"),
            Xi(name: "Elliptical Trainer"),
            Xi(name: "Rowing Machine"),
            Xi(name: "Punching Bag"),
            Xi(name: "Boxing Gloves"),
            Xi(name: "Medicine Ball"),
            Xi(name: "Stability Ball"),
            Xi(name: "Stepper"),
            Xi(name: "Pilates Ring"),
            Xi(name: "Balance Board"),
            Xi(name: "Ab Roller"),
            Xi(name: "Skipping Rope"),
            Xi(name: "Gymnastic Rings"),
            Xi(name: "Battle Ropes"),
            Xi(name: "Agility Ladder"),
            Xi(name: "Suspension Trainer")
        ],
        Ni(name: "Outdoor Sports"): [
            Xi(name: "Bicycle"),
            Xi(name: "Helmet"),
            Xi(name: "Camping Tent"),
            Xi(name: "Sleeping Bag"),
            Xi(name: "Hiking Boots"),
            Xi(name: "Fishing Rod"),
            Xi(name: "Kayak"),
            Xi(name: "Life Jacket"),
            Xi(name: "Climbing Gear"),
            Xi(name: "Binoculars"),
            Xi(name: "Camping Stove"),
            Xi(name: "Backpack"),
            Xi(name: "Compass"),
            Xi(name: "Trekking Poles"),
            Xi(name: "Camping Lantern"),
            Xi(name: "Cooler"),
            Xi(name: "Hiking Backpack"),
            Xi(name: "Sleeping Pad"),
            Xi(name: "Camping Chair"),
            Xi(name: "Multi-Tool"),
            Xi(name: "Headlamp"),
            Xi(name: "Portable Water Filter"),
            Xi(name: "Hammock"),
            Xi(name: "Fire Starter"),
            Xi(name: "Insect Repellent"),
            Xi(name: "Sunscreen")
        ],
        Ni(name: "Water Sports"): [
            Xi(name: "Swimsuit"),
            Xi(name: "Goggles"),
            Xi(name: "Swim Cap"),
            Xi(name: "Snorkel"),
            Xi(name: "Flippers"),
            Xi(name: "Surfboard"),
            Xi(name: "Paddleboard"),
            Xi(name: "Life Jacket"),
            Xi(name: "Wetsuit"),
            Xi(name: "Diving Gear"),
            Xi(name: "Water Shoes"),
            Xi(name: "Kayak"),
            Xi(name: "Canoe"),
            Xi(name: "Wakeboard"),
            Xi(name: "Water Skis"),
            Xi(name: "Sailboat"),
            Xi(name: "Jet Ski"),
            Xi(name: "Inflatable Raft"),
            Xi(name: "Underwater Camera"),
            Xi(name: "Dry Bag"),
            Xi(name: "Swim Fins"),
            Xi(name: "Scuba Tank"),
            Xi(name: "Snorkeling Vest"),
            Xi(name: "Swim Buoy"),
            Xi(name: "Diving Mask"),
            Xi(name: "Swim Training Gear")
        ],
        Ni(name: "Winter Sports"): [
            Xi(name: "Ski"),
            Xi(name: "Ski Boots"),
            Xi(name: "Ski Poles"),
            Xi(name: "Snowboard"),
            Xi(name: "Snowboard Boots"),
            Xi(name: "Helmet"),
            Xi(name: "Goggles"),
            Xi(name: "Ski Jacket"),
            Xi(name: "Snow Pants"),
            Xi(name: "Gloves"),
            Xi(name: "Ski Socks"),
            Xi(name: "Snowshoes"),
            Xi(name: "Ice Skates"),
            Xi(name: "Hockey Stick"),
            Xi(name: "Hockey Puck"),
            Xi(name: "Sled"),
            Xi(name: "Snow Tube"),
            Xi(name: "Snowboard Binding"),
            Xi(name: "Ski Binding"),
            Xi(name: "Avalanche Beacon"),
            Xi(name: "Snow Shovel"),
            Xi(name: "Snow Probe"),
            Xi(name: "Backcountry Pack"),
            Xi(name: "Hand Warmers"),
            Xi(name: "Face Mask"),
            Xi(name: "Balaclava")
        ],
        Ni(name: "Racquet Sports"): [
            Xi(name: "Tennis Racket"),
            Xi(name: "Tennis Balls"),
            Xi(name: "Badminton Racket"),
            Xi(name: "Badminton Shuttlecocks"),
            Xi(name: "Squash Racket"),
            Xi(name: "Squash Balls"),
            Xi(name: "Racquetball Racket"),
            Xi(name: "Racquetball Balls"),
            Xi(name: "Table Tennis Paddle"),
            Xi(name: "Table Tennis Balls"),
            Xi(name: "Table Tennis Table"),
            Xi(name: "Pickleball Paddle"),
            Xi(name: "Pickleball Balls"),
            Xi(name: "Tennis String"),
            Xi(name: "Tennis Grip"),
            Xi(name: "Tennis Net"),
            Xi(name: "Badminton Net"),
            Xi(name: "Squash Goggles"),
            Xi(name: "Racquetball Goggles"),
            Xi(name: "Racquet Sports Bag"),
            Xi(name: "Tennis Ball Hopper"),
            Xi(name: "Court Shoes"),
            Xi(name: "Wristbands"),
            Xi(name: "Headbands")
        ]
    ]
]
