//
//  toysAndGames.swift
//  Sales
//
//  Created by José Ruiz on 8/7/24.
//

import Foundation

let toysAndGames: Categories = [
    Mi(name: "Toys and Games"): [
        Ni(name: "Children's Toys"): [
            Xi(name: "Action Figures"),
            Xi(name: "Dolls"),
            Xi(name: "Building Blocks"),
            Xi(name: "Toy Cars"),
            Xi(name: "Stuffed Animals"),
            Xi(name: "Educational Toys"),
            Xi(name: "Board Games"),
            Xi(name: "Puzzles"),
            Xi(name: "Outdoor Toys"),
            Xi(name: "Craft Kits"),
            Xi(name: "Plush Toys"),
            Xi(name: "Toy Trains"),
            Xi(name: "Remote Control Cars"),
            Xi(name: "Playsets"),
            Xi(name: "Toy Instruments"),
            Xi(name: "Interactive Toys"),
            Xi(name: "Robots"),
            Xi(name: "Learning Tablets"),
            Xi(name: "Pretend Play Sets"),
            Xi(name: "Toy Guns"),
            Xi(name: "Building Sets"),
            Xi(name: "Ride-On Toys"),
            Xi(name: "Toy Kitchens"),
            Xi(name: "Toy Tools"),
            Xi(name: "Toy Soldiers")
        ],
        Ni(name: "Board Games"): [
            Xi(name: "Strategy Games"),
            Xi(name: "Family Games"),
            Xi(name: "Party Games"),
            Xi(name: "Card Games"),
            Xi(name: "Dice Games"),
            Xi(name: "Cooperative Games"),
            Xi(name: "Trivia Games"),
            Xi(name: "Word Games"),
            Xi(name: "Tile Games"),
            Xi(name: "Classic Games"),
            Xi(name: "Role-Playing Games"),
            Xi(name: "Thematic Games"),
            Xi(name: "Eurogames"),
            Xi(name: "Deck-Building Games"),
            Xi(name: "Legacy Games"),
            Xi(name: "Miniature Games"),
            Xi(name: "Abstract Games"),
            Xi(name: "Children's Games"),
            Xi(name: "Party Card Games"),
            Xi(name: "Bluffing Games")
        ],
        Ni(name: "Video Games"): [
            Xi(name: "Action Games"),
            Xi(name: "Adventure Games"),
            Xi(name: "Role-Playing Games"),
            Xi(name: "Simulation Games"),
            Xi(name: "Strategy Games"),
            Xi(name: "Sports Games"),
            Xi(name: "Racing Games"),
            Xi(name: "Fighting Games"),
            Xi(name: "Puzzle Games"),
            Xi(name: "Music Games"),
            Xi(name: "Platformers"),
            Xi(name: "First-Person Shooters"),
            Xi(name: "Battle Royale"),
            Xi(name: "Open World Games"),
            Xi(name: "MMORPGs"),
            Xi(name: "Indie Games"),
            Xi(name: "VR Games"),
            Xi(name: "Multiplayer Games"),
            Xi(name: "Stealth Games"),
            Xi(name: "Survival Games")
        ],
        Ni(name: "Outdoor Toys"): [
            Xi(name: "Swing Set"),
            Xi(name: "Trampoline"),
            Xi(name: "Sandbox"),
            Xi(name: "Playhouse"),
            Xi(name: "Slide"),
            Xi(name: "Inflatable Pool"),
            Xi(name: "Kite"),
            Xi(name: "Water Gun"),
            Xi(name: "Jump Rope"),
            Xi(name: "Frisbee"),
            Xi(name: "Bubbles"),
            Xi(name: "Pogo Stick"),
            Xi(name: "Hopscotch Set"),
            Xi(name: "Outdoor Chalk"),
            Xi(name: "Garden Tools for Kids"),
            Xi(name: "Tree Swing"),
            Xi(name: "Swing Ball"),
            Xi(name: "Croquet Set"),
            Xi(name: "Tetherball Set"),
            Xi(name: "Outdoor Playhouse"),
            Xi(name: "Water Slide"),
            Xi(name: "Kids' Tents"),
            Xi(name: "Outdoor Climbing Toys"),
            Xi(name: "Scooter"),
            Xi(name: "Balance Bike")
        ],
        Ni(name: "Educational Toys"): [
            Xi(name: "STEM Toys"),
            Xi(name: "Science Kits"),
            Xi(name: "Math Games"),
            Xi(name: "Language Learning Toys"),
            Xi(name: "Geography Toys"),
            Xi(name: "Electronic Learning Toys"),
            Xi(name: "Engineering Kits"),
            Xi(name: "Art & Craft Kits"),
            Xi(name: "Robotics Kits"),
            Xi(name: "Musical Instruments"),
            Xi(name: "Building Sets"),
            Xi(name: "Reading Games"),
            Xi(name: "Flash Cards"),
            Xi(name: "Coding Toys"),
            Xi(name: "Microscopes"),
            Xi(name: "Telescopes"),
            Xi(name: "Anatomy Models"),
            Xi(name: "Puzzle Games"),
            Xi(name: "Nature Exploration Kits")
        ],
        Ni(name: "Arts & Crafts"): [
            Xi(name: "Painting Sets"),
            Xi(name: "Drawing Kits"),
            Xi(name: "Sculpting Clay"),
            Xi(name: "Crafting Kits"),
            Xi(name: "Knitting & Sewing Kits"),
            Xi(name: "Beading Sets"),
            Xi(name: "Origami Sets"),
            Xi(name: "Sticker Books"),
            Xi(name: "Coloring Books"),
            Xi(name: "Scrapbooking Kits"),
            Xi(name: "Jewelry Making Kits"),
            Xi(name: "Stamp Sets"),
            Xi(name: "DIY Craft Kits"),
            Xi(name: "Glue & Adhesives"),
            Xi(name: "Craft Scissors"),
            Xi(name: "Craft Papers"),
            Xi(name: "Markers & Crayons"),
            Xi(name: "Craft Paints"),
            Xi(name: "Easel Sets"),
            Xi(name: "Embroidery Kits")
        ]
    ]
]
